openapi: "3.0.0"
TelemetryEntry:
  type: object
  description: Telemetry Entry.
  properties:
    requestId:
      type: string
      description: Request Id
    timestamp:
      type: integer
      format: int64
      description: Timestamp of the entry, in milliseconds elapsed since UNIX epoch.
    mode:
      $ref: "./DecisioningMode.yaml#/DecisioningMode"
      description: Decisioning Mode for request
    execution:
      type: integer
      format: double
      description: Execution time in milliseconds.
    parsing:
      type: integer
      format: int64
      description: Response parsing time, in milliseconds elapsed since UNIX epoch.
    features:
      $ref: "./TelemetryFeatures.yaml#/TelemetryFeatures"
    request:
      $ref: "./TelemetryRequest.yaml#/TelemetryRequest"
